# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: likly@ilikly.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://final.ilikly.com # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
domain: https://github.com/likly/final-framework/blob/master
git:
  url: https://github.com/likly/final-framework
  domain: Github
final:
  version: 0.4.7-SNAPSHOT
  entities: META-INF/final.entities
# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  extensions:
    - autolink
    - footnotes
    - smart
theme: minima
encoding: UTF-8
plugins:
  - jekyll-feed
  - jekyll-coffeescript
  #  - jekyll-default-layout
  - jekyll-gist
#  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
#data_dir: datas
collections_dir: pages
collections:
  framework:
    output: true
  monitor:
    output: true
  json:
    output: true
  mybatis:
    output: true
  spring:
    output: true
  cache:
    output: true
#defaults:
#  - scope:
#      path: ""
#      type: "cache"
#    values:
#      layout: "post"
#      toc: true
#      module: "cache"
#  - scope:
#      path: ""
#      type: "json"
#    values:
#      layout: "post"
#      toc: true
#      module: "json"
# 插件配置
gist:
  noscript: false
readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: false
relative_links:
  enabled:     true
  collections: true
include:
  - data
toc:
  enable: true
  min_level: 2
  max_level: 4
  headers: h2,h3,h4,h5,h6
  list_class: ""
  item_class: "nav-item toc-entry"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
